"""add recipe instructions and cooking fields

Revision ID: 886c7a8b35ee
Revises: b3f76e418a18
Create Date: 2026-01-03 14:41:13.787407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886c7a8b35ee'
down_revision = 'b3f76e418a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cook_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('instructions')
        batch_op.drop_column('cook_min')
        batch_op.drop_column('prep_min')

    # ### end Alembic commands ###
