"""init core models

Revision ID: c65b303c8ff0
Revises: 
Create Date: 2026-01-03 06:33:18.913462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65b303c8ff0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('meal_plan_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_week_user_start')
    )
    with op.batch_alter_table('meal_plan_weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_weeks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_weeks_week_start'), ['week_start'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_user_id'), ['user_id'], unique=False)

    op.create_table('meal_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['meal_plan_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_groups_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_groups_week_id'), ['week_id'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=240), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('meal_group_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_group_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('planned_servings', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_group_id'], ['meal_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_group_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_group_recipes_meal_group_id'), ['meal_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_group_recipes_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_group_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_group_recipes_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_meal_group_recipes_meal_group_id'))

    op.drop_table('meal_group_recipes')
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('meal_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_groups_week_id'))
        batch_op.drop_index(batch_op.f('ix_meal_groups_day'))

    op.drop_table('meal_groups')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_user_id'))

    op.drop_table('recipes')
    with op.batch_alter_table('meal_plan_weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_weeks_week_start'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_weeks_user_id'))

    op.drop_table('meal_plan_weeks')
    op.drop_table('users')
    # ### end Alembic commands ###
